exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
    exclude: ^templates/
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
    exclude: ^templates/
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.9.0'  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
    exclude: ^templates/
    additional_dependencies:
    - types-requests
    - types-freezegun
    - types-python-dateutil
    - types-pkg_resources
    - types-PyYAML
    - types-tabulate
    - types-aiofiles

- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.2
  hooks:
  - id: pycln
    args: [--config=pyproject.toml]
    exclude: ^templates/

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint --j 4 --disable=duplicate-code,use-implicit-booleaness-not-comparison
    language: system
    types: [python]
    exclude: ^templates/
    args: [--disable=use-implicit-booleaness-not-comparison]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.10.1
  hooks:
    - id: pyupgrade
      args:
        - --py38-plus

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.7
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
